import test from 'node:test';import assert from 'node:assert/strict';import {detect,mask,validAadhaar,classifyByDetectors} from '../src/services/detectors.js';import {calculateRisk} from '../src/services/scoring.js';
import {validateAiJson,retryOnce} from '../src/services/aiValidation.js';
// Synthetic values only. Aadhaar checksum test vectors are invented and never represent real people.
test('Aadhaar requires Verhoeff checksum',()=>{assert.equal(validAadhaar('234567890124'),true);assert.equal(validAadhaar('234567890125'),false);assert.deepEqual(detect('234567890124'),{aadhaar:['234567890124'],pan:[],phone:[],upi:[],ifsc:[],email:[],dob:[],bank_account:['234567890124']})});
test('PAN validation and identifier detectors',()=>{assert.deepEqual(detect('ABCDE1234F').pan,['ABCDE1234F']);assert.deepEqual(detect('ABCDE12345').pan,[]);assert.deepEqual(detect('9876543210').phone,['9876543210']);assert.deepEqual(detect('person@example.com').email,['person@example.com']);assert.deepEqual(detect('person@example.com').upi,[]);assert.deepEqual(detect('clinic@upi').upi,['clinic@upi'])});
test('masks preserve only limited suffixes',()=>{assert.equal(mask('aadhaar','234567890124'),'XXXX XXXX 0124');assert.equal(mask('pan','ABCDE1234F'),'XXXXX1234X');assert.equal(mask('phone','9876543210'),'XXXXXXX210');assert.equal(mask('email','person@example.com'),'p***@***.com')});
test('deterministic classification floors identity sensitivity',()=>{assert.deepEqual(classifyByDetectors(['aadhaar'],'patient_id'),{category:'identity',sensitivity:'critical'})});
test('risk excludes resolved and accepted risks and caps at 100',()=>{assert.deepEqual(calculateRisk([{severity:'critical',status:'open',category:'identity'},{severity:'high',status:'in_progress',category:'health'},{severity:'critical',status:'resolved',category:'identity'},{severity:'low',status:'accepted_risk',category:'contact'}]),{score:30,breakdown:{identity:20,contact:0,financial:0,health:10,children:0,location:0,credentials:0,other:0}});assert.equal(calculateRisk(Array.from({length:8},()=>({severity:'critical',status:'open'}))).score,100)});
test('invented 200-row clinic sample is detected without persistence',()=>{const rows=Array.from({length:200},(_,i)=>{const base=`2${String(i+4000000000).padStart(10,'0')}`;let aadhaar='';for(let n=0;n<10;n++){if(validAadhaar(base+n)){aadhaar=base+n;break}}return {patient_name:`Synthetic Patient ${i+1}`,mobile:`9${String(i).padStart(9,'0')}`,aadhaar,dob:'12/03/1990',diagnosis_notes:'Synthetic seasonal allergy',guardian_name:`Synthetic Guardian ${i+1}`,upi_id:`patient${i}@upi`}});assert.equal(rows.length,200);assert.ok(rows.every(r=>validAadhaar(r.aadhaar)));assert.equal(rows.filter(r=>detect(r.aadhaar).aadhaar.length===1).length,200);assert.ok(rows.every(r=>detect(r.mobile).phone.length===1));assert.ok(rows.every(r=>detect(r.upi_id).upi.length===1));});
test('malformed AI JSON is rejected by schema validation',()=>{assert.throws(()=>validateAiJson('{bad json'));assert.throws(()=>validateAiJson('[{"field_name":"x","category":"unknown"}]'))});
test('AI request retries once, then returns a later valid response',async()=>{let attempts=0;const value=await retryOnce(async()=>{attempts++;if(attempts===1)throw Error('temporary failure');return 'ok'});assert.equal(value,'ok');assert.equal(attempts,2)});
