import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import {env} from '../config/env.js';
import {pool} from '../config/db.js';

const supported=new Set(['csv','xlsx','txt']);
const callback=(provider)=>`${env.CONNECTOR_API_URL||`http://localhost:${env.PORT}`}/api/connectors/${provider}/callback`;
const clientReturn=()=>env.CONNECTOR_CLIENT_URL||env.CLIENT_ORIGIN;
function configuration(){
 return {id:env.GOOGLE_OAUTH_CLIENT_ID,secret:env.GOOGLE_OAUTH_CLIENT_SECRET,ready:Boolean(env.GOOGLE_OAUTH_CLIENT_ID&&env.GOOGLE_OAUTH_CLIENT_SECRET&&/^[\da-f]{64}$/i.test(env.CONNECTOR_TOKEN_KEY))};
}
function crypt(value){const key=Buffer.from(env.CONNECTOR_TOKEN_KEY,'hex');const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([c.update(value,'utf8'),c.final()]);return [iv,c.getAuthTag(),data].map(x=>x.toString('base64url')).join('.')}
function decrypt(value){try{const [iv,tag,data]=value.split('.').map(x=>Buffer.from(x,'base64url'));if(!iv||!tag||!data)throw new Error('Invalid encrypted token');const d=crypto.createDecipheriv('aes-256-gcm',Buffer.from(env.CONNECTOR_TOKEN_KEY,'hex'),iv);d.setAuthTag(tag);return Buffer.concat([d.update(data),d.final()]).toString('utf8')}catch{throw Object.assign(new Error('PrivacyLens cannot unlock the saved Google connection. Disconnect Google Drive and connect it again. If this keeps happening, keep CONNECTOR_TOKEN_KEY unchanged in Railway.'),{status:401})}}
function providerUrl(){return 'https://oauth2.googleapis.com/token'}
export function connectorStatus(rows){return [{provider:'google',configured:configuration().ready,connected:rows.some(x=>x.provider==='google'),accountEmail:rows.find(x=>x.provider==='google')?.account_email||null}]}
export function authorizationUrl(_provider,user){const c=configuration();if(!c.ready)throw Object.assign(new Error('Google OAuth setup is incomplete. Configure the Google client and token encryption key in .env.'),{status:503});const state=jwt.sign({provider:'google',id:user.id,org_id:user.org_id},env.JWT_SECRET,{expiresIn:'10m'});const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',c.id);u.searchParams.set('redirect_uri',callback('google'));u.searchParams.set('response_type','code');u.searchParams.set('state',state);u.searchParams.set('scope','openid email https://www.googleapis.com/auth/drive.readonly');u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');return u.toString()}
export async function finishAuthorization(_provider,code,state){const payload=jwt.verify(state,env.JWT_SECRET);if(payload.provider!=='google')throw Object.assign(new Error('Invalid Google OAuth state'),{status:400});const c=configuration();if(!c.ready)throw Object.assign(new Error('Google OAuth setup is incomplete'),{status:503});const form=new URLSearchParams({client_id:c.id,client_secret:c.secret,code,redirect_uri:callback('google'),grant_type:'authorization_code'});const tokenRes=await fetch(providerUrl(),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!tokenRes.ok)throw Object.assign(new Error('Google authorization failed. Check the configured redirect URI and OAuth scopes.'),{status:400});const token=await tokenRes.json();if(!token.access_token)throw Object.assign(new Error('Google did not return an access token'),{status:400});const profileRes=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{authorization:`Bearer ${token.access_token}`}});if(!profileRes.ok)throw Object.assign(new Error('Could not read the connected Google account profile'),{status:400});const profile=await profileRes.json();const email=profile.email||'Connected Google account';await pool.query(`INSERT INTO workspace_connectors(org_id,provider,account_email,access_token_enc,refresh_token_enc,expires_at) VALUES($1,'google',$2,$3,$4,now()+($5::text||' seconds')::interval) ON CONFLICT(org_id,provider) DO UPDATE SET account_email=excluded.account_email,access_token_enc=excluded.access_token_enc,refresh_token_enc=COALESCE(excluded.refresh_token_enc,workspace_connectors.refresh_token_enc),expires_at=excluded.expires_at,updated_at=now()`,[payload.org_id,email,crypt(token.access_token),token.refresh_token?crypt(token.refresh_token):null,Math.max(60,Number(token.expires_in)||3600)]);return {org_id:payload.org_id,user_id:payload.id,email}}
async function connector(org){const r=await pool.query("SELECT * FROM workspace_connectors WHERE org_id=$1 AND provider='google'",[org]);if(!r.rowCount)throw Object.assign(new Error('Connect Google Drive first.'),{status:404});const row=r.rows[0];if(!row.expires_at||new Date(row.expires_at).getTime()<Date.now()+120000){if(!row.refresh_token_enc)throw Object.assign(new Error('The Google session expired. Reconnect this account.'),{status:401});const c=configuration();const form=new URLSearchParams({client_id:c.id,client_secret:c.secret,refresh_token:decrypt(row.refresh_token_enc),grant_type:'refresh_token'});const tr=await fetch(providerUrl(),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!tr.ok)throw Object.assign(new Error('The Google session expired. Reconnect this account.'),{status:401});const token=await tr.json();row.access_token_enc=crypt(token.access_token);row.expires_at=new Date(Date.now()+(Number(token.expires_in)||3600)*1000);await pool.query('UPDATE workspace_connectors SET access_token_enc=$1,refresh_token_enc=COALESCE($2,refresh_token_enc),expires_at=$3,updated_at=now() WHERE id=$4',[row.access_token_enc,token.refresh_token?crypt(token.refresh_token):null,row.expires_at,row.id])}return {...row,accessToken:decrypt(row.access_token_enc)}}
function extension(name,mime){const ext=(name||'').split('.').pop().toLowerCase();if(supported.has(ext))return ext;if(mime==='application/vnd.google-apps.spreadsheet')return 'xlsx';if(mime==='application/vnd.google-apps.document')return 'txt';return null}
export async function listRemoteFiles(org,_provider){const c=await connector(org);let items=[],pageToken;do{const u=new URL('https://www.googleapis.com/drive/v3/files');u.searchParams.set('pageSize','100');u.searchParams.set('fields','nextPageToken,files(id,name,mimeType,modifiedTime,size,webViewLink)');u.searchParams.set('q','trashed=false');if(pageToken)u.searchParams.set('pageToken',pageToken);let r;try{r=await fetch(u,{headers:{authorization:`Bearer ${c.accessToken}`}})}catch{throw Object.assign(new Error('Could not reach Google Drive. Check the server network connection and try again.'),{status:502,exposeError:true})}if(!r.ok){let reason='';try{const body=await r.json();reason=body.error?.message||''}catch{}if(r.status===401||r.status===403)throw Object.assign(new Error(reason?`Google Drive denied the file request: ${reason}`:'Google Drive denied access. Reconnect your Google account and confirm the Drive permission.'),{status:403,exposeError:true});throw Object.assign(new Error(reason?`Google Drive could not list files: ${reason}`:'Google Drive could not list files. Try again.'),{status:502,exposeError:true})}const data=await r.json();items.push(...(data.files||[]));pageToken=data.nextPageToken}while(pageToken&&items.length<500);return items.map(f=>({id:f.id,name:f.name,mimeType:f.mimeType||'',modifiedTime:f.modifiedTime||null,size:Number(f.size)||null,webUrl:f.webViewLink||null,extension:extension(f.name,f.mimeType||'')})).filter(f=>f.extension&&(!f.size||f.size<=env.MAX_UPLOAD_MB*1024*1024)).slice(0,500)}
export async function downloadRemoteFile(org,_provider,fileId,name,mimeType){const c=await connector(org);const ext=extension(name,mimeType);if(!ext)throw Object.assign(new Error('Only CSV, Excel workbooks, and text exports can be scanned right now.'),{status:415});const url=mimeType==='application/vnd.google-apps.spreadsheet'?`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}/export?mimeType=${encodeURIComponent('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}`:mimeType==='application/vnd.google-apps.document'?`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}/export?mimeType=text/plain`:`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?alt=media`;const response=await fetch(url,{headers:{authorization:`Bearer ${c.accessToken}`},redirect:'follow'});if(!response.ok)throw Object.assign(new Error('Could not download the selected file from Google Drive.'),{status:502});const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>env.MAX_UPLOAD_MB*1024*1024)throw Object.assign(new Error(`Selected file exceeds the ${env.MAX_UPLOAD_MB} MB scan limit.`),{status:413});return {originalname:(name||'connected-file').replace(/[\\/:*?"<>|]/g,'_').replace(/\.[^.]+$/,'')+'.'+ext,buffer:bytes,size:bytes.length}}
export async function disconnect(org,_provider){await pool.query("DELETE FROM workspace_connectors WHERE org_id=$1 AND provider='google'",[org])}
export const connectorRedirect=(_provider,status)=>`${clientReturn()}/connections?${status}=google`;
